[target.x86_64-unknown-linux-gnu]
# https://github.com/cross-rs/cross/issues/1689
pre-build = [
  "apt-get -y install gcc-10",
  "update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100",
]
