debug = false

[scraping]
max_proxies_per_source = 10
timeout = 5.0

[scraping.http]
enabled = false
urls = []

[scraping.socks4]
enabled = false
urls = []

[scraping.socks5]
enabled = false
urls = []

[discovery]
enabled = true
shodan_api_key = "test_key_placeholder"
search_query = "port:8080 proxy"
max_results = 5
timeout = 10.0

[checking]
check_url = "https://httpbin.org/ip"
max_concurrent_checks = 10
timeout = 5.0

[output]
path = "./test_out"
sort_by_speed = true

[output.txt]
enabled = true

[output.json]
enabled = false
include_asn = false
include_geolocation = false
